# Generated by Django 4.2.19 on 2025-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodentry",
            options={"verbose_name_plural": "Food Entries"},
        ),
        migrations.AlterModelOptions(
            name="fooditem",
            options={"verbose_name_plural": "Food Items"},
        ),
        migrations.AddField(
            model_name="fooditem",
            name="sugar",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
