# Generated by Django 4.2.19 on 2025-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_tracker",
            "0002_alter_foodentry_options_alter_fooditem_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                ],
                default="breakfast",
                max_length=9,
            ),
        ),
    ]
