# Generated by Django 4.2.19 on 2025-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0003_foodentry_meal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodentry",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                ],
                max_length=9,
            ),
        ),
    ]
